### ISSUE TITLE
[1.10.2] Worldgen StackOverflowException

### ISSUE THREAD

**Issue by mrAppleXZ** [Shadows-of-Fire/Plants#10]
fml-server-latest.log: https://gist.githubusercontent.com/mrAppleXZ/785ca068365bb1e43e4a3352de90b95f/raw/c59d6bd309d8a06ee9a24362f6f9b709a50db1ba/gistfile1.txt
Removing the Flowers mod fixes the problem.

**Comment by Shadows-of-Fire** [comment]
Lets see if the same fix to #9 fixes this one.

**Comment by Shadows-of-Fire** [comment]
Reopen if this issue persists.  If it does i will contact sponge to resolve.
