### ISSUE TITLE
Cascading world lag while someone was in a Crystal Forest(and just flying around) and then crash while breaking block with better builders wand

### ISSUE THREAD

**Issue by TheRealDadbeard** [Shadows-of-Fire/Plants#102]
Server just got crazy laggy then the person crashed. Heres Serverlog: https://pastebin.com/gcvL3fv5

And here from the client that crashed: https://paste.dimdev.org/iwazotimos.mccrash

The Person hit it with the Better Wands Wand.

**Comment by P3rf3ctXZer0** [comment]
Okay so this may be what I am experiencing minus the crash. @Shadows-of-Fire why does crystal forest lag game?

**Comment by Shadows-of-Fire** [comment]
Crystal forests do not cause cascading generation.  I just ran around in one for *forever* and nothing was raised.

**Comment by TheRealDadbeard** [comment]
This is a really old issue and most likely fixed itself via numerous updates to either this mod or forge handling things. I can't recall either having this issue I think or disabled those forests on my server.

Keep in mind that most run modpacks with more than one mod that can cause this.

**Comment by P3rf3ctXZer0** [comment]
@Shadows-of-Fire please couple it with Botania. Seperate niether lag - but together - also want to say sorry for not specifying.
