### ISSUE TITLE
[In-game bug] While exploring end's dimension, possible sound effect, or soundtrack bug involving plants2

### ISSUE THREAD

**Issue by alxcool** [Shadows-of-Fire/Plants#107]
Plants-1.12.2-2.10.3
Placebo-1.12.2-1.4.1
(may require to test again in a smaller pack as theses mods are not the only one listed. )
[latest.log](https://github.com/Shadows-of-Fire/Plants/files/2416268/latest.log)

This might not be too hard to reproduce. Could someone check if he encounter the same sound, or soundtrack  special effect than me while exploring new or old chunks in the end dimension?

How to reproduce.
A) Join a world, then explorer new (end island) chunk in the vanilla's end dimension.
B) Listen to ambient sound effect launched by any of the plants2's plants native of the end dimension, then pay attention until you hear any of the vanilla ambient soundtrack (any) start.
C) After a few seconds, one of either sound effect or soundtrack stop playing, then something weird happens.
C1) One of the sound is restarted at every game's tick. It sounds like the sound of a machine gun.
C2) After 3 sec, any sound effect, or ambient music stop, or is cancelled.
C3) After, I am still able to listen to endermen's reaction's and or animation sound effect, or I still receive them, [...], but hear no sound effects anymore coming out from any of the plants2's plants like.

Note, my first language is not English, so feel free to ask me to edit my request!

In the following days, I will try to reproduce this situation with less mods. So you don't have to ask me to do it ;).

**Comment by Shadows-of-Fire** [comment]
Thats unusual.  It sounds like something else is interfering with the sound system, but I'll look at it with just plants installed.

**Comment by alxcool** [comment]
Thk for your support! I've just launch a test loading only this mod, then realize that staying close to a plants block, won't trigger my bug.

By exploring new chunks inside the end dimension, I've encountered this difficulty, with or when listening to a single ambiant sound. Mostly, the last sec of a track, but I'm not sure which one. I guess there is only one track who may cause problems and its the last 10 sec of it. Might be : 
C:\Users\userName\AppData\Roaming\.minecraft\resources\newmusic\nuance1.ogg

Background : 
While exploring new chunks, I was paying attention to the start of any ambient sound. Then only the ending of a track, start to bug. I'm not sure which one cause the machine gun alike noise, for less than 2sec.

Conclusion : 
Here a few of my guess, it have nothing to do with your mod, so you could close this issue.
a) either my laptop suffered damage withing years and I may need new hardware.
Like if this bug may not be linked to minecraft and only happen while listening to a specific range of music note, or mix.
b) Might be a pilot issue
c) playing with many mods, by enabling, disabling some, may have corrupted my minecraft library or resources. I should head for a reinstall. As example, wither have no drops anymore.

Thk for the support!
