### ISSUE TITLE
Exception in server tick loop

### ISSUE THREAD

**Issue by shanebirley** [Shadows-of-Fire/Plants#108]
Ran into this problem after installing the mod on my server. The start up process tanks when it loads "plants2".

> Description: Exception in server tick loop
> 
> net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Plants (plants2)
> Caused by: java.lang.ExceptionInInitializerError
> 	at shadows.plants2.Plants2.preInit(Plants2.java:71)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.lang.reflect.Method.invoke(Unknown Source)
> 	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
> 	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.lang.reflect.Method.invoke(Unknown Source)
> 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
> 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
> 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
> 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
> 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
> 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
> 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
> 	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
> 	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.lang.reflect.Method.invoke(Unknown Source)
> 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
> 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
> 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
> 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
> 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
> 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
> 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
> 	at net.minecraftforge.fml.common.LoadController.redirect$onPost$zza000(LoadController.java:560)
> 	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
> 	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
> 	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:99)
> 	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333)
> 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125)
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
> 	at java.lang.Thread.run(Unknown Source)
> Caused by: java.lang.NullPointerException
> 	at shadows.plants2.block.BlockEnumSlab.getDouble(BlockEnumSlab.java:155)
> 	at shadows.plants2.block.BlockEnumSlab.func_149662_c(BlockEnumSlab.java:121)
> 	at net.minecraft.block.state.BlockStateContainer$StateImplementation.handler$onInit$bab00b(BlockStateContainer.java:1131)
> 	at net.minecraft.block.state.BlockStateContainer$StateImplementation.<init>(BlockStateContainer.java:181)
> 	at net.minecraft.block.state.BlockStateContainer.createState(BlockStateContainer.java:67)
> 	at net.minecraft.block.state.BlockStateContainer.<init>(BlockStateContainer.java:88)
> 	at net.minecraft.block.state.BlockStateContainer.<init>(BlockStateContainer.java:62)
> 	at shadows.plants2.block.BlockEnumSlab.func_180661_e(BlockEnumSlab.java:136)
> 	at net.minecraft.block.Block.<init>(Block.java:234)
> 	at net.minecraft.block.Block.<init>(Block.java:243)
> 	at shadows.placebo.block.BlockBasic.<init>(BlockBasic.java:21)
> 	at shadows.plants2.block.BlockEnumSlab.<init>(BlockEnumSlab.java:47)
> 	at shadows.plants2.block.forgotten.BlockCrystal$Slabs.<init>(BlockCrystal.java:228)
> 	at shadows.plants2.init.ModRegistry.lambda$static$1(ModRegistry.java:193)
> 	at shadows.placebo.util.EnumBlockFactory.<init>(EnumBlockFactory.java:16)
> 	at shadows.plants2.init.ModRegistry.<clinit>(ModRegistry.java:193)
> 	... 37 more

**Comment by Shadows-of-Fire** [comment]
While this crash report is badly formatted and next to useless, this issue is caused by another mod modifiying a vanilla class.  It's not an issue on my end.

**Comment by shanebirley** [comment]
Dude, you didn't have to be a jerk about this.
