### ISSUE TITLE
Might want to investigate this

### ISSUE THREAD

**Issue by Sunconure11** [Shadows-of-Fire/Plants#109]
https://pastebin.com/yph3bNyR

I was trying to get my heavily modded server back up, once more, so I could bug fix a patch for the Vanillafix devs, and this struck every time. The mod that loaded last before the error struck was this one.

**Comment by Shadows-of-Fire** [comment]
Something is loading a client class on dedicated, and generally when the error occurs like this, its not the last mod you see load, its the next mod in the load order.  Plants works fine on a dedicated server, so this isn't on my end.
