### ISSUE TITLE
Conflict with Quark

### ISSUE THREAD

**Issue by Zygus42** [Shadows-of-Fire/Plants#111]
Plants-1.12.2-2.10.4
Plants-Placebo-1.12.2-1.5.1
Quark-r1.5-144
Quark - AutoRegLib-1.3-24
forge-1.12.2-14.23.5.2806-installer-win

Crashes on startup:
[crash-2019-01-20_23.55.15-client.txt](https://github.com/Shadows-of-Fire/Plants/files/2776788/crash-2019-01-20_23.55.15-client.txt)

**Comment by P3rf3ctXZer0** [comment]
disable pots or update forge. I have quark and plants on my server.
