### ISSUE TITLE
Server Startup Errors - Forge 1.12.2 (2795)

### ISSUE THREAD

**Issue by smmmadden** [Shadows-of-Fire/Plants#112]
**Issue:** I'm trying to create a modpack to include all these mods once I get the server-side of things working without errors (at least on startup) for a single and multiplayer world setup.  

I've added the list of mods to my multiplayer server, restarted and it appears that Placebo is throwing a number of errors.  Two of the mods are mine (TmTmc-Gravels and TmTmc-OresAndMore).  I'm looking for a nice balance of mods which would add more resources to a given world right from the start once I get a good seed to use with them.  

I found the Plants mod and thought this would be a great addition.  I've also included these two in the [spreadsheet I manage]([https://docs.google.com/spreadsheets/d/1phbsKtVQ-3Eoa422uLi7xqPIK6c9yNsSJXjmwpeavZA/edit#gid=471376170]) for plugins and mods. :-)

**List of mods on Server**
![image](https://user-images.githubusercontent.com/10309346/51803786-e8b83a00-2226-11e9-80ea-37793146b526.png)
**List of mods on Client**
![image](https://user-images.githubusercontent.com/10309346/51803837-5f553780-2227-11e9-9223-dde8303eff27.png)

**Exception/Error/Warnings**
https://hastebin.com/atimanaweq.sql

**Server:** Minecraft Forge 1.12.2 Build 14.23.5.2795
**Client:** Minecraft Forge 1.12.2 Build 14.23.5.2795

Am I missing some other dependency or is this a known issue for the build I'm on?  Thanks! -Steve

**Comment by Shadows-of-Fire** [comment]
That's just forge complaining about a feature it implemented.  See, placebo replaces shapeless recipes in the game registry to improve performance (which is allowed by forge) but every time you do so it logs an error.
They aren't real errors, so you can just ignore them

**Comment by smmmadden** [comment]
Awesome - thanks for the quick reply. :-)
