### ISSUE TITLE
Blazing Orchid missing from the Directory of Plants.

### ISSUE THREAD

**Issue by kevinkjt2000** [Shadows-of-Fire/Plants#113]
https://github.com/Shadows-of-Fire/Plants/wiki/Directory-of-Plants does not have a link to documentation about the blazing orchid.

**Comment by Shadows-of-Fire** [comment]
Yeah, that wiki is incomplete, I had someone doing it but they never finished and I don't really have the time to compile the rest of the wiki.  Is there something you needed to know about it?

**Comment by kevinkjt2000** [comment]
I'm not sure really, but I believe found enough info in JEI.  Just wanted
to mention the plant was missing, since the list seems pretty complete
otherwise.

**Comment by Shadows-of-Fire** [comment]
Closing this as the wiki will need a complete revisit as of 3.x.x
