### ISSUE TITLE
[Bug] Stairs shadow glitch

### ISSUE THREAD

**Issue by ndrp** [Shadows-of-Fire/Plants#114]
There seems to be a glitch with stairs added by your mod that makes the corners have an ugly black shadow in some constellations. Here's an example screenshot: https://imgur.com/4Rzo3Hg.
I replaced the Incense Cedar stairs at that exact location with vanilla stairs, and the black spot went away, so I'm pretty sure that it should be caused by your mod. I think vanilla stairs had this problem too at some point, but Mojang eventually got around to fixing it. 
Edit: I'm using the version for 1.12.2, downloaded through Twitch Launcher.

**Comment by ndrp** [comment]
Nevermind, my

**Comment by ndrp** [comment]
Ok, I closed this because I replaced another stairs with vanilla stairs, and it didn't go away, so I thought I had made a mistake the first time. But it turns out it is caused by the Incense Cedar stairs _around_ it, so if I replace them as well it goes away.

**Comment by Shadows-of-Fire** [comment]
The stairs that Plants uses have nothing different code-wise than vanilla stairs, so I'm not sure if there's anything I can do about this.  This may just be a vanilla lighting bug.  You could try checking out Phosphor, which is a rewrite of the lighting engine, and may resolve this problem.
