### ISSUE TITLE
Question in reguards to Generation of flowers

### ISSUE THREAD

**Issue by Morpheus1101** [Shadows-of-Fire/Plants#13]
Are the flowers designed to spawn in such large clumps in the 1 area or more designed to be sporatic and more spread around ?

**Comment by Shadows-of-Fire** [comment]
All of those aspects are fully configurable, but I do believe the current defaults end up with sparse clusters, instead of spread out  areas.

**Comment by Morpheus1101** [comment]
okies, i will look into the config more for V5 of Dev :D
