### ISSUE TITLE
All plants can be placed only on Vanilla dirt and grass blocks + World Gen Issue

### ISSUE THREAD

**Issue by Erinbutt** [Shadows-of-Fire/Plants#15]
Using Latest Version of Plants-1.10.2-beta-0.8.2.jar

Plant's cannot be placed on blocks that they could be placed on in previous versions.
With BOP I am unable to place plants on Silty, Sandy and Loamy grass and dirt. Spawned into my world and had plants popping off of the Silty Soil blocks.

World gen in my current world with newly generated chunks has the plants generate in a large square with all the same types of plants...Not sure if its intentional?

**Comment by Shadows-of-Fire** [comment]
The huge square thing should've been removed as of 0.8.2, as for the BOP placements... I'll look into that one.

**Comment by Shadows-of-Fire** [comment]
Will be pushing to curseforge shortly.

**Comment by Shadows-of-Fire** [comment]
This odd generation issue is only present in 1.10.2, and I'm not entirely sure what's causing it.  The vanilla dirt only issue is fixed though.

**Comment by Shadows-of-Fire** [comment]
Oh, try deleting your old configuration file.  The default values changed.
