### ISSUE TITLE
Colliding entity with block

### ISSUE THREAD

**Issue by N1ghtWolf213** [Shadows-of-Fire/Plants#16]
I am having a problem with your cataplant causing this crash. It's either just a normal zombie or an infernal mobs zombie, I am not a pro at reading crash logs so here it is. Also I have Biomes O Plenty and I get this crash on both 0.8.2. and 0.8.3. (only versions I have tried) 1.10.2, modpack is FTB Beyond and I'm sure if you want to know the rest of the mods I'm using its all in the log as well. http://pastebin.com/5R6cGqXt

**Comment by Shadows-of-Fire** [comment]
Am I correct in assuming this is a dedicated server?

**Comment by N1ghtWolf213** [comment]
Yes this is a server.
