### ISSUE TITLE
plants should generate depending the biomes

### ISSUE THREAD

**Issue by Hypsellis** [Shadows-of-Fire/Plants#18]
The plants generate totally randomly in the different biomes, it creates many incoherences like pineapples in taiga. You should use biome types for generating the plants.

**Comment by mankra** [comment]
Any progress on this?

**Comment by Shadows-of-Fire** [comment]
Not really, it'd take quite a while and I don't really have the motivation to do it right now.

**Comment by Shadows-of-Fire** [comment]
This should be done when i rewrite the config.  All plants should have a configurable temperature range from which they can be generated in.  It'll happen after the Forge 1.12 registry rewrite, which should be shortly before forge goes stable.

**Comment by P3rf3ctXZer0** [comment]
@Wyn-Price feel like helping again XD

**Comment by Wyn-Price** [comment]
Ill look into it later. Right now im just gonna finish off part of my mod

**Comment by Hypsellis** [comment]
You should use Forge biome types. ;)

**Comment by Hypsellis** [comment]
Any progress on that ?

**Comment by Shadows-of-Fire** [comment]
No, not really.  It would require rewriting a lot of internals and _meh_

**Comment by Hypsellis** [comment]
It's why I had told to do at the beginning before to include more stuff, now you have more work to do for correcting it. :/

**Comment by Shadows-of-Fire** [comment]
Isn't it _just_ the pineapple you have a problem with t.t

**Comment by Hypsellis** [comment]
Not really, exotic flowers generate in cold biomes for example. You should use forge biome kind for generating your plants.

**Comment by Hypsellis** [comment]
I'm not sure to understand why it would such a big problem since you already did it for the trees.

**Comment by Hypsellis** [comment]
These issues should be really fixed for bushes and flowers.

**Comment by Sanofus** [comment]
What is to do to solve this?

**Comment by Hypsellis** [comment]
Surely rewrite a part of the way trees and flowers are generated and add a condition which check biomes using forge biome tags. I don't think it would be hard to do, but I understand nothing of how shadow coded this mod, the code is horribly made.

**Comment by Shadows-of-Fire** [comment]
Its not that it's difficult, it would just take forever, and it would be boring as hell.  I do not have the patience to go though all (150+) things in this mod and type them to biome dict tags.

**Comment by twoelk** [comment]
would a table in some external spreadsheet format that includes all plant names, proposed biomes and columns for min-max-temp, min-max-altitude, grow-on-blocks, needed-closeby-blocks etc be a start?  
or does such allready exist somewhere for this mod?

**Comment by Shadows-of-Fire** [comment]
Being implemented in 3.x.x https://github.com/Shadows-of-Fire/Plants/blob/3.x.x/src/main/java/shadows/naturalis/util/EnumGenType.java
