### ISSUE TITLE
[1.11.2] Game Crash when Picking Up Cataplant

### ISSUE THREAD

**Issue by birb-ebooks** [Shadows-of-Fire/Plants#21]
https://pastebin.com/7KdxBkEF - crash log

Using plants 2.0.0. I only now realized it says UNSUPPORTED in giant impossible-to-miss letters, but I figure I should let you know in case it's something that needs fixin'

Basically the game just totally crashes when I pick up cataplants. Not much else to it.

**Comment by Shadows-of-Fire** [comment]
Yeah, that build was created strictly for a modpack that needed access to the nether plants, but that error is *technically* caused by BoP throwing an invalid meta at the cataplant, but neither mod supports 1.11 anymore.  It won't happen in 1.12 though.

**Comment by birb-ebooks** [comment]
Aw dang, I was all excited for those trees and nether plants... Further incentive to upgrade to 1.12 I guess. I was hanging back waiting for Rockhounding to update (one of my two favorites, the other being this one <3), but I guess 1.11's at the end of its cycle :/

Oh well. Thanks for the quick response! And the great mod!

**Comment by Shadows-of-Fire** [comment]
If you do want to prevent that crash, disabling the Tool module will disable the cataplant.  That's the only thing in the module.
