### ISSUE TITLE
[1.12] Crash while registering OreDictionary during startup

### ISSUE THREAD

**Issue by birb-ebooks** [Shadows-of-Fire/Plants#23]
Crashlog: https://pastebin.com/fn1Eyw9z

Not sure what exactly the conflict is here, but it worked again when I removed Plants, so I'm thinking your mod is involved somehow.

**Comment by Shadows-of-Fire** [comment]
This actually appears to be an issue with Botany, I'll open an issue over there

**Comment by birb-ebooks** [comment]
Huh. It worked fine with Binnie's Mods still installed...

**Comment by birb-ebooks** [comment]
I did some more testing, and got the same crash on a version with only Plants, Binnies (and Forestry of course), and TinyProgressions. Binnies and Plants played nice together, but TinyProgressions threw everything into chaos.
Here's the crashlog for that: https://pastebin.com/5NyXw9kV

**Comment by Shadows-of-Fire** [comment]
See the last post on 24.
