### ISSUE TITLE
Crash related to BiomesOPlenty lilypad?

### ISSUE THREAD

**Issue by armuell** [Shadows-of-Fire/Plants#24]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ForgelinPlugin (Forgelin-1.5.1.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.2.jar)
  CTMCorePlugin (CTM-MC1.12-0.2.2.7.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  BetterFoliageLoader (BetterFoliage-MC1.12-2.1.10.jar)
  DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.7.2.jar)
  DummyPlugin (ForgeEndertech-1.12-3.0.1.0-build.0012.jar)
  TANLoadingPlugin (ToughAsNails-1.12-3.0.0.64-universal.jar)
  LoadingPlugin (ChunkAnimator-MC1.12-1.2.jar)
Contact their authors BEFORE contacting forge

// Oh - I know what I did wrong!

Time: 9/25/17 9:06 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Plants (plants2)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 32767
	at biomesoplenty.common.block.BlockBOPLilypad.func_176203_a(BlockBOPLilypad.java:108)
	at biomesoplenty.common.item.ItemBOPBlock.func_77667_c(ItemBOPBlock.java:85)
	at net.minecraft.item.Item.func_77657_g(Item.java:292)
	at net.minecraft.item.Item.func_77653_i(Item.java:362)
	at net.minecraft.item.ItemStack.func_82833_r(ItemStack.java:617)
	at com.kashdeya.tinyprogressions.main.TinyProgressions.registerOre(TinyProgressions.java:125)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_571_TinyProgressions_registerOre_OreRegisterEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:683)
	at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:628)
	at shadows.plants2.init.ModRegistry.oreDict(ModRegistry.java:253)
	at shadows.plants2.Plants2.init(Plants2.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:611)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:253)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:231)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:781)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:348)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1610607752 bytes (1535 MB) / 2963800064 bytes (2826 MB) up to 4772593664 bytes (4551 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx5120m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.0.2486 81 mods loaded, 81 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                   | Version                  | Source                                          | Signature                                |
	|:----- |:-------------------- |:------------------------ |:----------------------------------------------- |:---------------------------------------- |
	| UCHI  | minecraft            | 1.12.2                   | minecraft.jar                                   | None                                     |
	| UCHI  | mcp                  | 9.42                     | minecraft.jar                                   | None                                     |
	| UCHI  | FML                  | 8.0.99.99                | forge-1.12.2-14.23.0.2486.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHI  | forge                | 14.23.0.2486             | forge-1.12.2-14.23.0.2486.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHI  | ivtoolkit            | 1.3.3-1.12               | minecraft.jar                                   | None                                     |
	| UCHI  | adventurebags        | 0.6                      | ab-1.12-0.6r.jar                                | None                                     |
	| UCHI  | antiqueatlas         | 4.4.4                    | antiqueatlas-1.12-4.4.4.jar                     | None                                     |
	| UCHI  | antiqueatlasoverlay  | 1.2                      | antiqueatlas-1.12-4.4.4.jar                     | None                                     |
	| UCHI  | jei                  | 4.7.10.97                | jei_1.12.2-4.7.10.97.jar                        | None                                     |
	| UCHI  | chisel               | MC1.12-0.0.14.18         | Chisel-MC1.12-0.0.14.18.jar                     | None                                     |
	| UCHI  | mantle               | 1.12-1.3.1.21            | Mantle-1.12-1.3.1.21.jar                        | None                                     |
	| UCHI  | tconstruct           | 1.12-2.7.3.30            | TConstruct-1.12-2.7.3.30.jar                    | None                                     |
	| UCHI  | theoneprobe          | 1.4.18                   | theoneprobe-1.12-1.4.18.jar                     | None                                     |
	| UCHI  | immersiveengineering | 0.12-72                  | ImmersiveEngineering-0.12-72.jar                | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| UCHI  | natura               | 1.12-4.3.0.17            | Natura-1.12-4.3.0.17.jar                        | None                                     |
	| UCHI  | betterwithmods       | 1.2.9-1.11.2             | BetterWithMods-1.12-2.0.10.jar                  | None                                     |
	| UCHI  | appleskin            | 1.0.8                    | AppleSkin-mc1.12-1.0.8.jar                      | None                                     |
	| UCHI  | base                 | 3.3.0                    | base-1.12-3.3.0.jar                             | None                                     |
	| UCHI  | baubles              | 1.5.1                    | Baubles-1.12-1.5.1.jar                          | None                                     |
	| UCHI  | bedbugs              | @VERSION@                | BedBugs-1.12-1.0.1.jar                          | None                                     |
	| UCHI  | betterbuilderswands  | 0.11.1                   | BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar | None                                     |
	| UCHI  | betterfoliage        | 2.1.10                   | BetterFoliage-MC1.12-2.1.10.jar                 | None                                     |
	| UCHI  | betterplacement      | 1.0.0-1                  | BetterPlacement-1.0.0-1.jar                     | None                                     |
	| UCHI  | betterquesting       | 2.5.236                  | BetterQuesting-2.5.236.jar                      | None                                     |
	| UCHI  | bibliocraft          | 2.4.3                    | BiblioCraft[v2.4.3][MC1.12.0].jar               | None                                     |
	| UCHI  | biometweaker         | 3.1.306                  | BiomeTweaker-1.12.1-3.1.306.jar                 | bdea6e9d19f35da4858ffcc93210c6207dd590bd |
	| UCHI  | biomesoplenty        | 7.0.0.2291               | BiomesOPlenty-1.12-7.0.0.2291-universal.jar     | None                                     |
	| UCHI  | birdsnests           | 2.0.0                    | BirdsNests1.12-2.0.0.jar                        | None                                     |
	| UCHI  | bookshelf            | 2.1.443                  | Bookshelf-1.12.2-2.1.443.jar                    | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHI  | ceramics             | 1.12-1.3.2               | Ceramics-1.12-1.3.2.jar                         | None                                     |
	| UCHI  | chameleon            | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                        | None                                     |
	| UCHI  | chesttransporter     | 2.8.7                    | ChestTransporter-1.12-2.8.7.jar                 | None                                     |
	| UCHI  | chiselsandbits       | 14.7                     | chiselsandbits-14.7.jar                         | None                                     |
	| UCHI  | chunkanimator        | 1.2                      | ChunkAnimator-MC1.12-1.2.jar                    | None                                     |
	| UCHI  | shadowmc             | 3.8.0                    | ShadowMC-1.12-3.8.0.jar                         | None                                     |
	| UCHI  | clipboard            | @VERSION@                | Clipboard-1.12-1.3.0.jar                        | None                                     |
	| UCHI  | clumps               | 2.0.0                    | Clumps-3.0.0.jar                                | None                                     |
	| UCHI  | cookingforblockheads | 6.3.6                    | CookingForBlockheads_1.12.1-6.3.6.jar           | None                                     |
	| UCHI  | ctm                  | MC1.12-0.2.2.7           | CTM-MC1.12-0.2.2.7.jar                          | None                                     |
	| UCHI  | custommainmenu       | 2.0.8                    | CustomMainMenu-MC1.12.2-2.0.8.jar               | None                                     |
	| UCHI  | dailies              | 1.12-6                   | dailies-1.12-6.jar                              | None                                     |
	| UCHI  | darkutils            | 1.7.173                  | DarkUtils-1.12.2-1.7.173.jar                    | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHI  | dsurround            | 3.4.7.2                  | DynamicSurroundings-1.12.2-3.4.7.2.jar          | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| UCHI  | presets              | 3.4.7.2                  | DynamicSurroundings-1.12.2-3.4.7.2.jar          | None                                     |
	| UCHI  | elevatorid           | 1.3.4                    | ElevatorMod-1.12-1.3.4.jar                      | None                                     |
	| UCHI  | shetiphiancore       | 3.5.2                    | shetiphiancore-1.12.0-3.5.2.jar                 | None                                     |
	| UCHI  | endertanks           | 1.6.0.2                  | endertanks-1.12.0-1.6.0.2.jar                   | None                                     |
	| UCHI  | extrabitmanipulation | 1.12-3.2.1               | ExtraBitManipulation-1.12-3.2.1.jar             | None                                     |
	| UCHI  | extrautils2          | 1.0                      | extrautils2-1.12-1.6.3.jar                      | None                                     |
	| UCHI  | fairylights          | 2.1.1                    | fairylights-2.1.1-1.12.jar                      | None                                     |
	| UCHI  | fastleafdecay        | v13                      | FastLeafDecay-v13.jar                           | None                                     |
	| UCHI  | flatcoloredblocks    | mc1.12-6.5               | flatcoloredblocks-mc1.12-6.5.jar                | None                                     |
	| UCHI  | forgeendertech       | 1.12-3.0.1.0             | ForgeEndertech-1.12-3.0.1.0-build.0012.jar      | None                                     |
	| UCHI  | forgelin             | 1.5.1                    | Forgelin-1.5.1.jar                              | None                                     |
	| UCHI  | fw                   | 1.6.0                    | FullscreenWindowed-1.12-1.6.0.jar               | None                                     |
	| UCHI  | gravestone           | 1.10.0                   | gravestone-1.10.0.jar                           | None                                     |
	| UCHI  | hopperducts          | 1.5                      | hopperducts-mc1.12-1.5.jar                      | None                                     |
	| UCHI  | inventorypets        | 1.4.9.8                  | inventorypets-1.12-1.4.9.8.jar                  | None                                     |
	| UCHI  | inventorytweaks      | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                        | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCHI  | ironchest            | 1.12-7.0.31.818          | ironchest-1.12-7.0.31.818.jar                   | None                                     |
	| UCHI  | jaff                 | 1.7_for_1.12             | JustAFewFish-1.7_for_1.12.jar                   | None                                     |
	| UCHI  | jeresources          | 0.8.3.23                 | JustEnoughResources-1.12-0.8.3.23.jar           | None                                     |
	| UCHI  | longfallboots        | 1.2.1a                   | longfallboots-1.2.1a.jar                        | None                                     |
	| UCHI  | netherportalfix      | 5.3.9                    | NetherPortalFix_1.12.1-5.3.9.jar                | None                                     |
	| UCHI  | openglider           | @VERSION@                | OpenGlider-1.12-1.0.1.jar                       | None                                     |
	| UCHI  | harvestcraft         | 1.12.1c                  | Pam's HarvestCraft 1.12.1c.jar                  | None                                     |
	| UCHE  | plants2              | 2.0.1                    | Plants-2.0.1.jar                                | None                                     |
	| UCHI  | platforms            | 1.4.0.1                  | platforms-1.12.0-1.4.0.1.jar                    | None                                     |
	| UCHI  | reccomplex           | 1.4.5                    | RecurrentComplex-1.4.5.1.jar                    | None                                     |
	| UCHI  | rustic               | 0.4.2.1                  | rustic-0.4.3.jar                                | None                                     |
	| UCHI  | simplecorn           | 2.3.2                    | SimpleCorn1.12-2.3.2.jar                        | None                                     |
	| UCHI  | simplytea            | 1.4                      | simplytea-1.4.jar                               | None                                     |
	| UCHI  | bq_standard          | 2.4.134                  | StandardExpansion-2.4.134.jar                   | None                                     |
	| UCHI  | storagedrawers       | 1.12-5.2.5               | StorageDrawers-1.12.1-5.3.2.jar                 | None                                     |
	| UCHI  | tp                   | 1.12                     | tinyprogressions-1.12-3.2.6.jar                 | None                                     |
	| UCHI  | topaddons            | 1.12-0.15.1              | topaddons-1.12-0.15.1.jar                       | None                                     |
	| UCHI  | toughasnails         | 3.0.0.64                 | ToughAsNails-1.12-3.0.0.64-universal.jar        | None                                     |
	| UCHI  | veinminer            | 0.38.1                   | VeinMiner-1.12-0.38.1.639+134fb1e.jar           | None                                     |
	| UCHI  | veinminermodsupport  | 0.38.1                   | VeinMiner-1.12-0.38.1.639+134fb1e.jar           | None                                     |
	| UCHI  | waddles              | 0.5.6                    | Waddles-1.12.2-0.5.6.jar                        | None                                     |
	| UCHI  | waystones            | 4.0.15                   | Waystones_1.12.1-4.0.15.jar                     | None                                     |

	Loaded coremods (and transformers): 
ForgelinPlugin (Forgelin-1.5.1.jar)
  
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.2.jar)
  shetiphian.asm.ClassTransformer
CTMCorePlugin (CTM-MC1.12-0.2.2.7.jar)
  team.chisel.ctm.client.asm.CTMTransformer
IvToolkit (IvToolkit-1.3.3-1.12.jar)
  
BetterFoliageLoader (BetterFoliage-MC1.12-2.1.10.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.7.2.jar)
  org.blockartistry.DynSurround.asm.Transformer
DummyPlugin (ForgeEndertech-1.12-3.0.1.0-build.0012.jar)
  
TANLoadingPlugin (ToughAsNails-1.12-3.0.0.64-universal.jar)
  toughasnails.asm.transformer.CropDecayTransformer
  toughasnails.asm.transformer.EntityRendererTransformer
  toughasnails.asm.transformer.WorldTransformer
LoadingPlugin (ChunkAnimator-MC1.12-1.2.jar)
  lumien.chunkanimator.asm.ClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 382.05' Renderer: 'GeForce GTX 750 Ti/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- theoneprobeIntegration (Enabled/Not Forced)

	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaDecorative (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)

**Comment by Shadows-of-Fire** [comment]
This appears to be similar to #23 which I'm pretty sure is tiny progressions at fault (maybe the final mod in the stack for not handling meta 32k properly, but still)
Tiny Progressions is making this methid call, and since its closed source with no issue tracker, nit much I can do about it.

**Comment by Shadows-of-Fire** [comment]
Yeah, no, this is entirely on tiny progressions.
```
  @SubscribeEvent
  public void registerOre(OreDictionary.OreRegisterEvent event)
  {
    logger.debug(event.getOre().getDisplayName());
  }
```
this does not need to be happening at all.

Going to also close #23 and fault it to tiny progressions.
