### ISSUE TITLE
question about cascading world gen 

### ISSUE THREAD

**Issue by beesyndicate** [Shadows-of-Fire/Plants#33]
sorry looked for you on twitter b/c this didn't seem like the right place to ask this but couldn't find you 
do you see a lot of cascading world gen lag caused by plants?

[FML]: Plants loaded a new chunk (97, -24  Dimension: 0) during chunk population, causing cascading worldgen lag.

**Comment by Shadows-of-Fire** [comment]
It should be very sparse, if at all.  I'm having a hard time sourcing where it's coming from.  But it is certainly not frequent.
Unless, that is, you're near a flower forest.  Then it's _everywhere_

**Comment by Shadows-of-Fire** [comment]
Should no longer be an issue.
