### ISSUE TITLE
Compatability with Dooglamoo Worlds

### ISSUE THREAD

**Issue by Deshiba** [Shadows-of-Fire/Plants#35]
When using Dooglamoo Worlds terrain generation in conjunction with Plants, only vanilla flowers spawn.

Opened this[ issue ](https://minecraft.curseforge.com/projects/dooglamoo-worlds/issues/7)on both sides.

**Comment by Shadows-of-Fire** [comment]
Weird.  The flowers are generated on an event, so if that mod isn't properly posting the event for their biomes, it won't work.  Gonna close this because it's on their end.
