### ISSUE TITLE
how do i get cotton in survival?

### ISSUE THREAD

**Issue by forestasog** [Shadows-of-Fire/Plants#36]
all the plants, can't find. XD

**Comment by Shadows-of-Fire** [comment]
You need to find a Wild Cotton plant.  It is a harvestable bush and as such is harvested on right click.  It spanws like anything else, naturally and via plantball.

**Comment by forestasog** [comment]
does it have to mature or something? because i tried breaking and right clicking it and it doesn't seem to drop anything.  i'm on mod version 1.10.2-beta-0.8.5

**Comment by Shadows-of-Fire** [comment]
Yeah, just let it sit there for some time.  It need light, but not water or anything.
