### ISSUE TITLE
This recipe makes no sense

### ISSUE THREAD

**Issue by ghost** [Shadows-of-Fire/Plants#39]
![weird dye recipe](https://user-images.githubusercontent.com/25916106/32405916-b042481a-c16e-11e7-809a-43264a8e66e7.png)

Shouldn’t this give you pink dye?

**Comment by raphydaphy** [comment]
good job shado

**Comment by Shadows-of-Fire** [comment]
Yeah... it'll be changed back to pink once I get a cyan plant.

**Comment by PapiDimmi** [comment]
Same with this one. Shouldn’t this give you grey dye?

![weird dye recipe 2](https://user-images.githubusercontent.com/25916106/32989491-67045f94-cd17-11e7-98c7-88a9fe00d6ac.png)
