### ISSUE TITLE
[Bug]Cataplant Pickup Crash

### ISSUE THREAD

**Issue by Xogue** [Shadows-of-Fire/Plants#40]
Attempting to pick up a cataplant after breaking it with my hand crashed the game in a single player world.  Here is the crash report:
[crash-2017-11-07_16.31.56-server.txt](https://github.com/Shadows-of-Fire/Plants/files/1451746/crash-2017-11-07_16.31.56-server.txt)

**Comment by Shadows-of-Fire** [comment]
The 1.11.2 version of Plants 2 is not supported, as per the filename.
