### ISSUE TITLE
Crash: Caught exception from Plants (plants2)

### ISSUE THREAD

**Issue by mysteryblock** [Shadows-of-Fire/Plants#41]
Every version of plants 2 after 1.2.0 gives me this error:

 

"The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Plants (plants2)"

 

I've continuously tried every new forge version on 1.12.2, as well as every new plants version. I always end up going back to v1.2.0 of plants as it does not give me this error.

**Comment by Shadows-of-Fire** [comment]
Provide the crash report file via https://gist.github.com or this issue will be closed.

**Comment by mysteryblock** [comment]
https://gist.github.com/mysteryblock/144bb4196b8eaa101699d89424520c0d

**Comment by Shadows-of-Fire** [comment]
Update Tiny Progressions.
