### ISSUE TITLE
Logs cannot be smelted into Charcoal, Wood cannot be used for planks, doors.

### ISSUE THREAD

**Issue by JaSpr** [Shadows-of-Fire/Plants#42]
v1.12, 2.1.1
Pack: ATM3, v4.5

**Comment by Shadows-of-Fire** [comment]
In resolution to this issue:
Charcoal recipes have been added
Wood -> plank recipes were already works, so...?
There are no door variants for these woods, that is not a bug.

**Comment by JaSpr** [comment]
Oh, I meant planks could not be used for slabs.  Not wood > planks... that did already work.

**Comment by JaSpr** [comment]
Also, I think some of the recipes that use any type of planks or any type of logs (for example) don't work because the Plants logs and plants planks don't extend the generic minecraft logs and planks. I  could be wrong on that.
