### ISSUE TITLE
Blacklist oreDict

### ISSUE THREAD

**Issue by Krhymez** [Shadows-of-Fire/Plants#45]
Could you add oreDict compatibility to the plant ball blacklist.
I would like to blacklist all tree saplings. Harvestcraft and other mods that adds trees.

Is there a way currently to disable entire mods from working with plant balls?

**Comment by Shadows-of-Fire** [comment]
So, an oredict blacklist is not really possible, but yeah.  You can blacklist modids.  Any string in the blacklist without a `:` in the name is treated as a modid.

**Comment by Krhymez** [comment]
ok, thanks i got it now.

harvestcraft
twilightforest

I used Craft tweaker to find these lists, but i then noticed it was just the first part of modids.  Thanks.
