### ISSUE TITLE
[Idea] Toggle Vanilla Flower forest?

### ISSUE THREAD

**Issue by SirChamomile** [Shadows-of-Fire/Plants#46]
Love the mod! Really adds character to vanilla biomes when BOP is not used, however, I'd love the option to turn off the mod flowers in flower forests. The vanilla palette is very tight, and I think it spoils the effect if too many colors are seen everywhere.

**Comment by Shadows-of-Fire** [comment]
`B:"Flower Forests"=true` has been there since the feature was added...

**Comment by SirChamomile** [comment]
Brilliant! I thought I had tried this and it didn't work. Guess I was mistaken :)
