### ISSUE TITLE
Can't place plants from Plants in Quark colored flower pots

### ISSUE THREAD

**Issue by armuell** [Shadows-of-Fire/Plants#48]
Any chance this mod could support Quark's colored flower pots?

**Comment by Shadows-of-Fire** [comment]
Unlikely, I have to replace the normal flowerpot to achieve this.  But maybe.

**Comment by armuell** [comment]
I will hope for a maybe 👍 

I put in a suggestion for forge here: http://www.minecraftforge.net/forum/topic/61973-flowerpot-hook/

**Comment by Shadows-of-Fire** [comment]
Deciding against this one, Inspirations appears to have my flowerpot functionality beat anyway, so rip.
