### ISSUE TITLE
[1.12.2] Tried to disable spawn in certain biomes

### ISSUE THREAD

**Issue by JonasCiss** [Shadows-of-Fire/Plants#50]
I tried to disable the spawn in the biomes of Abyssalcraft but it failed. What do I exactly have to add to the config file to prevent spawns? 

I tried this. 

plantball {
    # A list of blacklisted registry names, or modids.  Strings without a ":" will be treated as modids. [default: ]
    S:"Plantball Blacklist" <
	Abyssalcraft
	abyssalcraft
	abyssalcraft:Darklands
	abyssalcraft:Coralium Infested Swamp
	abyssalcraft:Darklands Forest
	abyssalcraft:Darklands Highland
	abyssalcraft:Darklands Mountain
	abyssalcraft:Darklands Plains
     >
}

**Comment by Shadows-of-Fire** [comment]
Thats not how that works, that cfg prevents use of the Plantball item.  It has nothing to do with biomes.
