### ISSUE TITLE
[Suggestion] [Request] [1.12.2] Adding blacklist or whitelist for spawnareas

### ISSUE THREAD

**Issue by JonasCiss** [Shadows-of-Fire/Plants#51]
I have some biomes in my modpack that should look dark and poor but I can't prevent Plants spawing there. So I would like to suggest to add a blacklist or whitelist to add these biomes. 
I think that would be a very useful feature also in the future to get along with other mods,

**Comment by Shadows-of-Fire** [comment]
2.3.0
