### ISSUE TITLE
Tree leaves are opaque

### ISSUE THREAD

**Issue by ElvenChaos** [Shadows-of-Fire/Plants#52]
All Plants2 tree leaves do not allow light to pass through, causing the inside of the block to appear black and for the leaves to block all light.

Plants2 2.2.2
Forge 2584

**Comment by Shadows-of-Fire** [comment]
You know now that you mention it... That may be why my crystal stuff keeps looking weird.

**Comment by ElvenChaos** [comment]
This includes the crystal leaves, I tested that while I was going through to see which leaves were affected (all of them). Fixing this seems like a crystal-clear solution to the weirdness :P
