### ISSUE TITLE
[1.12.2] Add fences, stairs, etc for mod planks

### ISSUE THREAD

**Issue by KorDum** [Shadows-of-Fire/Plants#53]
Can you add fences, stairs, slabs for mod planks?
It'll be cool for buildings!

It does not take much time and you can see how it is done from my mod
https://github.com/KorDum/TotemDefender/tree/master-mc1.12.2/src/main

**Comment by Shadows-of-Fire** [comment]
Once 1.13 lands they will be present.

**Comment by KorDum** [comment]
Sorry, I didn't fully understand. Is it planned to enter only the version of Minecraft 1.13+?

**Comment by Shadows-of-Fire** [comment]
That would be the plan, yeah.

**Comment by KorDum** [comment]
Can I add them with PR?

**Comment by Shadows-of-Fire** [comment]
It's highly unlikely I accept a PR.  There are reasons behind my decision to not include them for 1.12.  Notably, the block id limit.

**Comment by KorDum** [comment]
Very doubtful excuse, yeah =) After all, you can always add their disabling in the config.
Well, I will work in my fork.

**Comment by Shadows-of-Fire** [comment]
In light of the delay for 1.13/1.14, this will likely happen for 1.12

**Comment by KorDum** [comment]
Oh thanks for hope!

**Comment by KorDum** [comment]
Thank you very much for additional building blocks!
