### ISSUE TITLE
reprint and translate 

### ISSUE THREAD

**Issue by YangYangJun** [Shadows-of-Fire/Plants#59]
Excuse me，
Can I reprint your mod at the mcbbs forum in China, or can I translate your mod into Chinese?
Forum URL：http://www.mcbbs.net/portal.php

**Comment by Shadows-of-Fire** [comment]
I believe there already is a zh_CN lang file, but it might be a bit outdated.  You can do whatever on the chinese forum.  I'd ask you link to curseforge where possible, but I understand that might not really be possible due to golden shield.

**Comment by YangYangJun** [comment]
Thank you for allowing, I will write and encourage players to curseforge the original address to download, but I do not know if I can use China's network disk backup download, because most people can not link curseforge or need 3 to 5 minutes waiting time.
