### ISSUE TITLE
[1.12.2] Crystal Forest Biome Not Compatible with Lost Cities Floating Isle Config or Forestry

### ISSUE THREAD

**Issue by MokahTGS** [Shadows-of-Fire/Plants#60]
So when using Plants and Lost Cities and Forestry together, I've noticed that when the world gen is happening I'm getting the land blocks made out of Larchwood Stairs instead of actual land in Crystal Forest biomes.  Trees and plants still generate as they should, just the land is made of stairs.

Screenshot: https://www.dropbox.com/s/bqn61yniglfgzo0/2018-02-13_12.53.34.png?dl=0

Plants v2.4.0
Placebo v1.2.0
Lost Cities v2.0.1
Forestry v5.8.0.243

Not sure what the issue is, but it's sure weird.

**Comment by Shadows-of-Fire** [comment]
Im about 93% sure that's world corruption at work there...  Unless you can reproduce it on new maps after a game restart, its world corruption.

**Comment by MokahTGS** [comment]
Well considering that it was a new test world, made just after starting the game, not sure how it can be world corruption.

**Comment by Shadows-of-Fire** [comment]
Well... then this will certainly be fun to source.

**Comment by Shadows-of-Fire** [comment]
This issue can only really be caused by something going horribly wrong in the registry,  any chance you could start up the game, make a broken world like this and send me the fml-client-latest.log on gist?

**Comment by Shadows-of-Fire** [comment]
Pretty sure its a corrupted registry.

**Comment by MokahTGS** [comment]
Still getting this with Cyrstal Forest Biomes generating as fences, gates, or other blocks.  I even have the CF biome turned off in the config.

**Comment by Shadows-of-Fire** [comment]
If you have the biome turned off in the config it is never even registered  (as of 2.6).  That is literally impossible.  There is literally nothing I can do about this,

**Comment by Shadows-of-Fire** [comment]
Thinking about it, you don't have Not Enough ID's installed or anything, do you?

**Comment by MokahTGS** [comment]
Yes, as do every player that has a lot of mods.  Anything I can fix?

**Comment by Shadows-of-Fire** [comment]
Yeah so that thing hacks into the world save quite a bit...  It is entirely unsupported.  2.6.0's crystal forest toggle will now not register the biome to fix some issues with BoP and any other worldtype that is setup incorrectly, so turning it off should work as expected.

**Comment by MokahTGS** [comment]
Well turning off NotEnoughIDs is not an option.  You can't have large mod packs without it.
