### ISSUE TITLE
[1.12.2] Wrong light on plants in pots

### ISSUE THREAD

**Issue by KorDum** [Shadows-of-Fire/Plants#62]
See screenshots:
in 2.4.0 all OK:
![image](https://user-images.githubusercontent.com/1331559/36244960-9440517c-1239-11e8-8e63-b9835abad422.png)

in 2.5.0
![image](https://user-images.githubusercontent.com/1331559/36244595-fcfacb54-1237-11e8-8e18-7f9a744153fd.png)

At first I thought that the problem in forge https://github.com/MinecraftForge/MinecraftForge/issues/4746

**Comment by KorDum** [comment]
Yes, without optifine in 2.5.0 light looks like fine. With optifine, the flowers look faded :)

**Comment by raphydaphy** [comment]
dont use optifine it breaks rendering in a lot of mods

**Comment by Shadows-of-Fire** [comment]
Well, nothing I can do about optifine breaking the lighting.  I forget if optifine has a config to re-enable the forge lighting pipeline, but if it doesn't, oh well.

**Comment by KorDum** [comment]
How did it happen that in 2.4.0 everything is OK?

**Comment by Shadows-of-Fire** [comment]
2.4.0 doesn't dynamically create the flower pot models at runtime, it literally was a couple thousand line json file hardcoded to a bunch of things.  The vanilla lighting pipeline (which optifine appears to re-enable) has issues with dynamic generation, apparently.  If OF has a config to enable the forge pipeline, it'll work just fine.

**Comment by KorDum** [comment]
Thanks for answer!

**Comment by mezz** [comment]
There is a pretty old bug open for Optifine/Forge here if you want to follow it in case something happens:
https://github.com/MinecraftForge/MinecraftForge/issues/3091

**Comment by Shadows-of-Fire** [comment]
Force disabling AO appears to cause it to be fine under the Vanilla pipe, but I didn't ever test it with OF.
@KorDum You should go check with OF under 2.5.2 and see what it looks like.

**Comment by KorDum** [comment]
![image](https://user-images.githubusercontent.com/1331559/36296669-78c4b3d6-12ff-11e8-8aa3-97c537ecb0e2.png)

No, no changes.

**Comment by Shadows-of-Fire** [comment]
Huh.  Wonder what OF does then.  Disabling the Forge pipeline doesn't cause the lighting errors for me after the AO changes, but OF already disables the forge pipe...  Oh well.

**Comment by KorDum** [comment]
Is there any small hope for correction? :)

**Comment by Shadows-of-Fire** [comment]
You could try disabling the `forgeLightPipelineEnabled` in Forge.cfg, but that shouldn't do anything unless optifine's modid isn't actually `optifine`.
