### ISSUE TITLE
[1.12.2] [Enhancement] Baneberries aren't poisonous.

### ISSUE THREAD

**Issue by NotAVerb** [Shadows-of-Fire/Plants#63]
I've found at least two berries with adverse effects. Pokeweed berry and flameberry.
Shouldn't baneberries, and any poisonous berries I've missed (like nightshade), also debilitate the player in some way?
Maybe Inflict a few seconds of poison effect?

**Comment by Shadows-of-Fire** [comment]
Yeah, I think they did at one point, but they appear to not currently. I need to go back and check over what needs to.

**Comment by Shadows-of-Fire** [comment]
Alright, here are the changes on this one.
`Horsenettle Fruit (Deadly)` -> 90% chance of Wither II for 900 ticks
`Climbing Nightshade Berries (Unhealthy)` -> 90% chance of Nausea III for 200 ticks
`Black Nightshade Berries` -> Edible when ripe, no change
`Baneberries (Very Deadly)` -> 100% chance of Wither III for 500 ticks
