### ISSUE TITLE
crystal block is hardly coded

### ISSUE THREAD

**Issue by Hypsellis** [Shadows-of-Fire/Plants#65]
I wanted to integrate crystal leave, logs, and chunks to better folliage, but all the classes are in a same class, not really clear, and in different folder, and integration doesn't work well for everything.

**Comment by Shadows-of-Fire** [comment]
wat

**Comment by Hypsellis** [comment]
The different crystal blocks are in a same class, and the integration into better folliage isn't easy notably for integrating te crystal chunk into crop list, since it's at the base of the primary class, and not one of the class inside this class. I know it's not really clear, it's not easy to explain.

**Comment by Shadows-of-Fire** [comment]
I'm not really understanding a word of this...
If you want to access the subclasses by name, the syntax is Class$SubClass

**Comment by Hypsellis** [comment]
You never used Better Folliage it seems. ^^'

**Comment by Hypsellis** [comment]
I know I shouldn't judge, but you nested classes inside another, and that it's really not the best. BetterFoliage takes the full class name in whitelist. Hapilly the nested classes extend your other classes, shadows.plants2.block.BlockEnumLeaves is enough for adding the plant leaves into BetterFoliage leaves whitelist, same for logs, bushes, saplings... But it's not the case for crystal shards for example, wich are at the base of crystal class, and not one the nested class, and add BlockCrystal inside BetterFoliage config doesn't work. Frankly if you still didn't understand, I'm sorry, I can't explain it better.

**Comment by Shadows-of-Fire** [comment]
I just told you before the syntax for a subclass is Class$SubClass...
IE Crystal Leaves are `shadows.plants2.block.forgotten.BlockCrystal$Leaves`
