### ISSUE TITLE
Crystal dirt should let grow bushes, flowers, saplings, and grass

### ISSUE THREAD

**Issue by Hypsellis** [Shadows-of-Fire/Plants#66]
Currently the crystal dirt doesn't behave like dirt, and let only crystal plant grow on it. Crystal grass should grow on it too.

**Comment by Shadows-of-Fire** [comment]
That is intentional

**Comment by Hypsellis** [comment]
Ok then. But you could add crystal grass that would spread on crystal dirt. ;)
