### ISSUE TITLE
[Question] How can I disable Aphrirerot produce pearls?

### ISSUE THREAD

**Issue by KorDum** [Shadows-of-Fire/Plants#67]
The plant is very beautiful, but gives a lighter way to get pearls.
How can I disable Aphrirerot produce pearls?

**Comment by Shadows-of-Fire** [comment]
You cannot, but do you really need to...?  At that point you're already in the end, pearls don't matter.

**Comment by KorDum** [comment]
Yes, there are crafts in my modpack, tied on this =)

**Comment by KorDum** [comment]
Thank you very much!
