### ISSUE TITLE
Vanilla plant growth behavior config option [idea]

### ISSUE THREAD

**Issue by xkforce** [Shadows-of-Fire/Plants#70]
I am currently working on a mod pack that aims to add variety to Minecraft but in a manner consistent with the vanilla game.  For example, 2 block tall flowers can be duplicated in vanilla with the application of bone meal.  Applying bone meal to grass generates flowers appropriate to that particular biome etc.  Ideally I'd like some means of retaining that behavior with all plants that are in the pack including plants2.
If it's not likely/feasible for plants2 to have an option like that, is there some alternative means of closely matching that behavior?

**Comment by Shadows-of-Fire** [comment]
Technically the plantball does those things for Plants blocks

**Comment by xkforce** [comment]
Yes I know it does... that's the point.  Why reinvent the wheel by adding a new item to do what bone meal should already be able to do?

**Comment by Shadows-of-Fire** [comment]
Because I don't have control over bonemeal, and some of my things react to bonemeal for actual growth, not plant duplication.  Furthermore, bonemeal could never bring my plants into the world without me spamming the biome flower lists with my own plants, which is pointless.
