### ISSUE TITLE
[1.12.2] Double plant not place on ground

### ISSUE THREAD

**Issue by KorDum** [Shadows-of-Fire/Plants#75]
I can not plant tall plants on the ground:
`plants2:double_0:*`
`plants2:double_harvest:*`

I tested on simple modpack only with:
- Forge 14.23.2.2611
- Placebo 1.3.1
- Plants 2.6.4

![image](https://user-images.githubusercontent.com/1331559/37297527-f4568a6e-262e-11e8-9373-0c3a693f5949.png)

**Comment by KorDum** [comment]
Hi! Where is update? :)

**Comment by raphydaphy** [comment]
its been five days, if you want a new build that badly just compile it yourself
