### ISSUE TITLE
invalid.name

### ISSUE THREAD

**Issue by NotAVerb** [Shadows-of-Fire/Plants#77]
Something's broken
![2018-03-15_00 07 41](https://user-images.githubusercontent.com/30223331/37443856-96414976-2806-11e8-9e0f-5801617ab2ec.png)

MC 1.12.2
Plants 2.6.4

**Comment by Shadows-of-Fire** [comment]
That's actually a compat recipe to support the migration of the old crystal planks to the new ones. It'll be removed eventually.
