### ISSUE TITLE
Runtime Exception: Invalid id 256 - maximum id range exceeded

### ISSUE THREAD

**Issue by Lightkeks** [Shadows-of-Fire/Plants#78]
Hey, i've started up Minecraft and seen this. [https://pastebin.com/eY1iBdMe](url)
This just confuses me. I want to use your mods too, so, would you like to look into it?

**Comment by raphydaphy** [comment]
Uh that's a lot of coremods AND foamfix, does this happen with just plants or without certain mods?

**Comment by Lightkeks** [comment]
i can tell it happens with TheRealp455w0rd [https://minecraft.curseforge.com/members/TheRealp455w0rd](url)'s mods too, i am going to test, why it happens sorry to tell :/

**Comment by Shadows-of-Fire** [comment]
If you are exceeding an ID range it means you have too many of something installed.  In this case, its biomes.
