### ISSUE TITLE
Feature Request: Can you make the world generation disable able

### ISSUE THREAD

**Issue by BakermanLP** [Shadows-of-Fire/Plants#8]
Hello there,

I love your mod and the really nice plants. Also the Botania module seems to be great.

And now to my Feature Request:
- Can you please make the world generation / world decorator disable able?

This seems to be a silly feature request, but in my configuration all world generation is done by another mod. And this seems to interfer with your mod. The generation time of a new world is now about 3 times longer than befor. 

Also a little crash report involving plants was created on leaving the world:
https://gist.github.com/BakermanLP/a26f34a3e1d4960b5b817fac9f65213e

Thanks for reading this

Michael (aka BakermanLP)

**Comment by Shadows-of-Fire** [comment]
setting all 4 of the generator control cdgs to -1 or 0 should have the same effect but yeah that sounds doable.  Also, that crash rep is terrain control at fault.

**Comment by Shadows-of-Fire** [comment]
Added 0.5.3
