### ISSUE TITLE
Thermal Foundation issue

### ISSUE THREAD

**Issue by Akitori** [Shadows-of-Fire/Plants#82]
https://i.gyazo.com/thumb/1200/b1501b26201d578de5b25c3fc84c4453-png.jpg

Yeah that's basically it in a shell nut. Tries to find a sapling that doesn't exist.

**Comment by Shadows-of-Fire** [comment]
The thermal handling is all on their side, so you'll have to report it to them

**Comment by KingLemming** [comment]
Hrm. Did you remove this one? When I added the recipe, it did exist at the time.

**Comment by Shadows-of-Fire** [comment]
Oh, maybe.  For the early stages of the crystal forest (pre-implementation, but the blocks were there) the crystal sapling was still split into two variants as a result of my automatic tree stuff...  There's only actually a single sapling `plants2:crystal_sapling`, which has a 30% chance to grow dark.

**Comment by KingLemming** [comment]
No problem. :) If it's gone, I'll take it out.
