### ISSUE TITLE
Excalibur Crash

### ISSUE THREAD

**Issue by FallenEagle1** [Shadows-of-Fire/Plants#84]
This was found first in the ATM3 modpack, and then was tested on a custom modpack to remove all other mods.

Forge: 14.23.3.2674 and 14.23.3.2679
Plants: 2.8.2 and 2.8.4
Botania: r1. 10-354

All the Mods 3 5.9.4b

Basically anytime the sword is swung at a mob, minecraft crashes. This can be done on both singleplayer worlds and multiplayer worlds.

Crash Report: https://pastebin.com/RKiMF1dc

**Comment by Shadows-of-Fire** [comment]
seems like botania updated.  bleh
