### ISSUE TITLE
Cryptic Block IDs

### ISSUE THREAD

**Issue by difquin** [Shadows-of-Fire/Plants#86]
This might be a WorldEdit-specific issue, but regardless, I'm having trouble targeting blocks from Plants by way of id in WorldEdit. "plants2:cosmetic_0" gives an error, same goes for "plants2:harvest". I've looked through the Plants source code to figure out, if your internal IDs differ from the ones visible inside the game, but the appear to be identical.
My mod folder includes other modes, such as Botania and Forestry, and WorldEdit takes no issue with "botania:flower", "forestry:resources" - or any of the native MCs "red_flower,yellow_flower".
Any idea as to how to get a hold of your blocks?

**Comment by Shadows-of-Fire** [comment]
I don't know how worldedit works, but pretty much everything in plants has block names identical to the placer item (exception of crops, which have no itemblock, only seeds).

I'll answer any questions presented, but I don't know the source of the issue.
