### ISSUE TITLE
Mod compatibility with chisels and bits

### ISSUE THREAD

**Issue by Demonox** [Shadows-of-Fire/Plants#88]
I tried to make items using the black kauri wood in conjunction with chisels and bits, but it appears this mod isn't fully compatible.  The bits have no collision or hitbox and act like water when you walk through them.  The pack I was using is ATM3 if that means anything.

**Comment by Shadows-of-Fire** [comment]
That... what.  I don't even comprehend how that could be possible.

**Comment by Gardnem6** [comment]
Is there anything i can send you to figure out whether 1) its actually your mod and 2) what the root of the issue may be?

**Comment by Shadows-of-Fire** [comment]
@AlgorithmX2 any idea why something would act like this?  There's not even any references to water in [the block's class](https://github.com/Shadows-of-Fire/Plants/blob/master/src/main/java/shadows/plants2/block/BlockEnumLog.java), so I don't have any clue how this could be happening.

**Comment by AlgorithmX2** [comment]
I don't know, tried it myself and neither the log, or the planks is behaving for me in this way chiseled or not chiseled.

It must be some other mod conflicting some how. C&B enables fluid physics only when a FluidRegistry.getRegisteredFluids() returns that block. it grabs all the validStates for the blocks and uses that list of states as a list of fluids.

Seems like another mod is somehow returning your block, and thus its states as a fluid.

**Comment by Demonox** [comment]
Is there anything I can do to help narrow down the source of the issue then?  I'm a software engineer by trade but I don't know much about minecraft mods behind the scenes.  It seems odd because they otherwise interact fine and it's just the wood from the Plants mod.  And in ATM3 there's a lot of mods to narrow down...

**Comment by Shadows-of-Fire** [comment]
I don't know...  There's no way its from my end, so you would have to try removing things until it stopped acting like a fluid.

**Comment by Demonox** [comment]
I see.  Thank you for the help.  I'll let you know if I find the culprit.

**Comment by AlgorithmX2** [comment]
Doing a binary search though the mods usually helps ( remove half, load, test, remove half, load test...  switching to adding half when it reproduces )

That said load time can be prohibitive, and its going to take a while regardless most likely.

**Comment by AlgorithmX2** [comment]
This should be fixed in the latest build of C&B 14.22
