### ISSUE TITLE
[Request] Adding Biome Colour Support (maybe Optifine)

### ISSUE THREAD

**Issue by Sanofus** [Shadows-of-Fire/Plants#89]
If you walk around a world you will often find plants of the Plants mod which colours don't match to its environment. I would like to ask if it is possible to add support for that. 

![2018-05-11_17 36 53](https://user-images.githubusercontent.com/26455012/40881836-6c6ebc8c-66d1-11e8-8da2-ba9cfe433629.png)
![2018-05-12_23 49 56](https://user-images.githubusercontent.com/26455012/40881837-7454a038-66d1-11e8-98d0-13af8bd1670e.png)

**Comment by Shadows-of-Fire** [comment]
Duplicate of #18 
(Unlikely to happen as this would take forever to do, and it would be incredibly boring)
