### ISSUE TITLE
[1.12.2] Blackslist did not work

### ISSUE THREAD

**Issue by Sanofus** [Shadows-of-Fire/Plants#90]
I added the following to the blacklist but I had no effect. 
# A list of biomes that Plants will not try to generate in. [default: [minecraft:river]]
    S:"Biome Blacklist" <
        minecraft:river
		abyssalcraft:darklands
		abyssalcraft:darklands_forest
		abyssalcraft:darklands_plains
		abyssalcraft:darklands_hills
		abyssalcraft:darklands_mountains
		abyssalcraft:coralium_infested_swamp
     >

![2018-06-03_02 57 22](https://user-images.githubusercontent.com/26455012/40882553-0ba48b74-66e6-11e8-87e3-227892049a29.png)
![2018-06-03_04 15 58](https://user-images.githubusercontent.com/26455012/40882554-0bbf7d62-66e6-11e8-9bb1-fb207dcd5014.png)
![2018-06-03_02 57 11](https://user-images.githubusercontent.com/26455012/40882555-0bd74a8c-66e6-11e8-8846-701d7ac2e6d0.png)

**Comment by Shadows-of-Fire** [comment]
Working on it.  I thought it was working properly, but upon inspection the bushes (and trees) don't even look at the Biome blacklist, and it doesn't log any errors.  Fix should be up soon.  The blacklist should correctly work in the next update, and any incorrect entries will log an error.

**Comment by Sanofus** [comment]
Thank you. :)
