### ISSUE TITLE
Disabling Wild Cotton

### ISSUE THREAD

**Issue by chland** [Shadows-of-Fire/Plants#96]
I'm currently setting up a little modpack and i'm trying to keep duplicate content to a minimum. Because of that I wanted to disable the Wild Cotton plants (and only use the ones from Harvestcraft).

But I noticed that there doesn't seem to be a config-setting to disable it. Neither for "Wild Cotton" nor for "apocynum_c".

I tried adding

`B:"Allow plants2:harvest_0[type=apocynum_c]"=false`

to the `plants_blocks.cfg` file but that didn't seem to work, either. Did I overlook something?

**Comment by Shadows-of-Fire** [comment]
Odd.  That should block its generation.

**Comment by Shadows-of-Fire** [comment]
For whatever reason it appeared to be sharing a config key with another block that wasn't its own.  This has been corrected (and more states should use their proper names now), but it may break some existing entries.
