### ISSUE TITLE
Plants generate with snowlayer on Top

### ISSUE THREAD

**Issue by ben-mkiv** [Shadows-of-Fire/Plants#97]
Hi, noticed this when creating a map with Plants mod today =>

![plants with snow layer](https://i.imgur.com/Lrq8nLZ.png)

Worldgenerator is OTG with Biome Bundle, so it might be some crossmod issue?!

modversion: plants-1.12.2-2.9.2
OTG 1.12.2 - v7

**Comment by Shadows-of-Fire** [comment]
I don't generate snow, so that's not on my end.
