### ISSUE TITLE
Plants not machine harvest-able.

### ISSUE THREAD

**Issue by Yamza** [Shadows-of-Fire/Plants#98]
Plants-1.12.2-2.9.2
Tested on All The Mods 3 (5.9.8d)

Please make plants harvest-able by machines.

Tested with the following:
Cyclic Harvester: Fail
EnderIO Farming Station: Fail
AA Farmer: Fail
Mechanical User: Works

**Comment by Shadows-of-Fire** [comment]
I assume you're referring to the right click harvest bushes, which are not crops in the tradtional sense.  Since forge lacks an interface to determine what is a "crop" that mods can harvest, the cyclic harvester and the enderio farming station will have to add support from their side.  I can, however, make it work with ActuallyAdditions, which I'll go do.

**Comment by PrinceOfAmber** [comment]
Forge absolutely does not have a /good consistent/ way to identify crop blocks.  But it does have a decent way that Cyclic (and other harvesting) probably use

- Have a BlockState property called Age with a min and max value, so its fully grown at max.  See BlockCrops class
`public static final PropertyInteger AGE = PropertyInteger.create("age", 0, 7);`
So any other mod can just say "does this blockstate have age? is it fully grown? Ok i know what to do now"

It looks like you already are doing this so ill have to look into my side to see what else I can do 


https://github.com/Shadows-of-Fire/Plants/blob/b63519cd2e9c1b23e381bbc14c15315367f65867/src/main/java/shadows/plants2/block/BlockEnumCrop.java#L38


My code in case you are curious (basically lots of hardcoded blocks with special cases followed by standard age property handling)
https://github.com/PrinceOfAmber/Cyclic/blob/6c8a7a51e2204f8879a35a4e3158665f3e5772ba/src/main/java/com/lothrazar/cyclicmagic/core/util/UtilHarvester.java#L210

**Comment by Shadows-of-Fire** [comment]
The crops in question here are not traditional crops, that class works fine with your harvester, the classes needing support are BlockEnumHarvestBush, BlockEnumNethetHarvest and BlockEnumDoubleHarvestBush

**Comment by Shadows-of-Fire** [comment]
The three classes I just named do not have age, nor seeds.  They strictly have a fruit bool (and in the case of the double bush, an upper bool)
