### ISSUE TITLE
Compatability with Rannuncarpus(Botania)

### ISSUE THREAD

**Issue by Yamza** [Shadows-of-Fire/Plants#99]
Plants-1.12.2-2.9.2
Tested on All The Mods 3 (5.9.8d)

When dropping Nightshade next to a Rannuncarpus, a Carolina Horsenettle is planted.
When dropping Carolina Horsenettle, a Saffron is planted.
When dropping Saffron, a Wine Raspberry Bush is planted.
Dropping a Wine Raspberry Bush works as expected.

**Comment by Shadows-of-Fire** [comment]
Don't think I can do anything about that.  Botania is making an assumption that the ItemStack metadata matches the placed block metadata, which isn't true for those.
